apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking-deployment
  labels:
    app: ticket-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-booking
  template:
    metadata:
      labels:
        app: ticket-booking
    spec:
      containers:
        - name: ticket-booking
          image: laxmisharany6/ticket-booking:latest  # replace with your image (or use imagePullPolicy)
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
