apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
spec:
  selector:
    app: ticket-booking
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
